build-server: 
	gcc server.c -o server -lws2_32

build-server-linux:
	gcc serverLinux.c -o serverLinux

build-client:
	gcc client.c -o client -lws2_32

run-server:
	./server 

run-server-linux:
	./serverLinux

run-client:
	./client
